services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api
      - server

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ALKO_URL=${ALKO_URL}
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/healthcheck.sh:/usr/local/bin/healthcheck.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5