CREATE TABLE IF NOT EXISTS products (
    number INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bottlesize VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    priceGBP DECIMAL(10, 2) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    orderamount INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cache_status (
    id INT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(50) NOT NULL,
    user VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO cache_status (status, user) VALUES ('initial', 'system') ON DUPLICATE KEY UPDATE timestamp = CURRENT_TIMESTAMP;