CREATE TABLE IF NOT EXISTS products (
    number INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bottlesize VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    priceGBP DECIMAL(10, 2) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    orderamount INT DEFAULT 0
);